version: "3.3"

services:
  web:
    image: $IMAGE_TAG:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:25000"
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_PASSWORD
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME