version: "3.3"

services:
  web:
    image: nbasov3/homework26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8000:80"
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME